export const CREATE_TODO_PENDING = 'Index/CREATE_TODO_PENDING';
export const CREATE_TODO_SUCCESS = 'Index/CREATE_TODO_SUCCESS';
export const DELETE_TODO_PENDING = 'Index/DELETE_TODO_PENDING';
export const DELETE_TODO_SUCCESS = 'Index/DELETE_TODO_SUCCESS';
export const GET_TODOS_PENDING = 'Index/GET_TODOS_PENDING';
export const GET_TODOS_SUCCESS = 'Index/GET_TODOS_SUCCESS';
export const UPDATE_TODO_PENDING = 'Index/UPDATE_TODO_PENDING';
export const UPDATE_TODO_SUCCESS = 'Index/UPDATE_TODO_SUCCESS';
